/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Clases.InfoParcelas;
import Clases.Simplex;
/**
 *
 * @author trifo
 */
public class Principal extends javax.swing.JFrame {
    
    InfoParcelas i;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonCargar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelArchivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaInformacion = new javax.swing.JTextArea();
        botonProcesar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaRespuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Planificación de cosecha de hortalizas: ");

        jLabel2.setText("Seleccione un archivo:");

        botonCargar.setText("Cargar");
        botonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarActionPerformed(evt);
            }
        });

        jLabel3.setText("Archivo seleccionado: ");

        labelArchivo.setText("         ");

        areaInformacion.setColumns(20);
        areaInformacion.setRows(5);
        jScrollPane1.setViewportView(areaInformacion);

        botonProcesar.setText("Procesar");
        botonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesarActionPerformed(evt);
            }
        });

        jLabel4.setText("Respuesta:");

        areaRespuesta.setColumns(20);
        areaRespuesta.setRows(5);
        jScrollPane2.setViewportView(areaRespuesta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(botonCargar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelArchivo))
                            .addComponent(botonProcesar)
                            .addComponent(jLabel4))
                        .addGap(0, 184, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonProcesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(this);
        File archivo=chooser.getSelectedFile();
        int linea = 1;
        int numParcelas = 0;
        int[] duracionCosecha = new int[0];
        int sumaDuracion = 0;
        int[][] utilidadEsperada = new int[0][0]; 
        String aux;
        boolean error = false;
        try{
            if(archivo!=null)
            {     
                FileReader archivos= new FileReader(archivo);
                BufferedReader br=new BufferedReader(archivos);
                while((aux=br.readLine())!=null)
                {
                    areaInformacion.append(aux.trim() + "\n");
                    if(linea == 1){
                        numParcelas = Integer.parseInt(aux.trim());
                        duracionCosecha = new int[numParcelas];
                        linea++;
                    }
                    else if(linea == 2){
                        StringTokenizer st = new StringTokenizer(aux.trim()," ");
                        for(int i = 0; i < numParcelas; i++){
                            duracionCosecha[i] = Integer.parseInt(st.nextToken());
                        }
                        linea++;
                    }
                    else if(linea == 3){
                        sumaDuracion = Integer.parseInt(aux.trim());
                        utilidadEsperada = new int[numParcelas][sumaDuracion];
                        linea++;
                    }
                    else{
                        StringTokenizer st = new StringTokenizer(aux.trim()," ");
                        for(int i = 0; i < sumaDuracion; i++){
                            utilidadEsperada[linea-4][i] = Integer.parseInt(st.nextToken());
                        }
                        linea++;
                    }
                }
                br.close();
            }    
        }
        catch(IOException ex){
            error = true;
            JOptionPane.showMessageDialog(this,
           "\nNo se ha encontrado el archivo",
                 "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e){
            error = true;
            JOptionPane.showMessageDialog(this,
           "\nOcurrio un error inesperado, verifique el archivo",
                 "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }
        finally{
            if(!error){
                if(archivo!=null) labelArchivo.setText(archivo.getPath());
                i = new InfoParcelas(numParcelas, duracionCosecha, sumaDuracion, utilidadEsperada);
            }  
            else{
                
            }
        }
    }//GEN-LAST:event_botonCargarActionPerformed
 
    private void botonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesarActionPerformed
        // TODO add your handling code here:
        String aux ="";
        boolean quit = false;
        float[][] f = i.tablaSimplex();
        float[][] standardized =  {
                { 1,   1,    1,  0,   4},
                { 1,   3,    0,  1,   6},
                {-3,  -5,    0,  0,   0}
        };
        Simplex s = new Simplex(i.getNumRestricciones(), i.getNumVariables());
        s.fillTable(f);
        s.print();
        System.out.println("------------------------------");
        while(!quit){
            Simplex.ERROR err = s.compute();

            if(err == Simplex.ERROR.IS_OPTIMAL){
                s.print();
                quit = true;
            }
            else if(err == Simplex.ERROR.UNBOUNDED){
                System.out.println("---Solution is unbounded---");
                quit = true;
            }
        }
                /*
        for (int j = 0; j < f.length; j++) {
            for(int k = 0; k < f[j].length; k++){
                aux+= f[j][k] + " ";
            }
            aux+="\n";
        }*/
        System.out.println(aux);
    }//GEN-LAST:event_botonProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaInformacion;
    private javax.swing.JTextArea areaRespuesta;
    private javax.swing.JButton botonCargar;
    private javax.swing.JButton botonProcesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelArchivo;
    // End of variables declaration//GEN-END:variables
}
